### PR TITLE
Added the ability to set what the command is. Also added a .gitignore.

### PR DESCRIPTION
**Pull request by wherkamp**
Just so you know why? In my server I don't want the island command to be ai? I am not making an acid island. it is just gonna be an island in the water. So the acid doesn't fit it.

### CODE REVIEW

**Comment by tastybento** [comment]
Seems useful. Thanks.

**Comment by Poslovitch** [comment]
I would have liked to see this as a WorldSetting though.

**Comment by wherkamp** [comment]
Thx for the merge. P.S I think your Config API is freaking awesome :).

**Comment by Poslovitch** [comment]
Thanks. We'll continue working on improving this one, but I personally think it's already reached a rather interesting quality.

Would you mind me making your PR more general by allowing all addons to implement itthe?

**Comment by wherkamp** [comment]
Sure, so you want all addons to have the ability to set the command?

**Comment by Poslovitch** [comment]
Exactly. There is something called "WorldSettings" in BentoBox. Addons that implement it are basically gamemodes, such as AcidIsland and BSB. Therefore, putting the command thing there would make more sense.

**Comment by tastybento** [comment]
Also, there's an issue with how other addons will hook into the commands. Right now, it's done explicitly using the command name. e.g., for the Level add-on:

```
        // AcidIsland hook in
        this.getPlugin().getAddonsManager().getAddonByName("AcidIsland").ifPresent(a -> {
            CompositeCommand acidIslandCmd = getPlugin().getCommandsManager().getCommand("ai");
            if (acidIslandCmd != null) {
                new IslandLevel(this, acidIslandCmd);
                new IslandTop(this, acidIslandCmd);
                CompositeCommand acidCmd = getPlugin().getCommandsManager().getCommand("acid");
                new AdminLevel(this, acidCmd);
                new AdminTop(this, acidCmd);
            }
        });
```

There are two ways this could be handled:

1. The Level add-on could have a config settings (in config.yml) that will list out the add-on and the associated admin and player command.
2. The Level add-on can use the WorldSettings API to just hook into "the admin command" or the "the player command"

Number 2 may be best, but there's an issue where a game mode has more than one command. For example, it may have /island and /plateau and /ocean. In that case, a WorldSetting for commands should be a list of commands that are available. We can't assume there's only one.

So, I'm thinking that Number 1 will be the better one because then the add-on command can be applied to any specific command.

Thoughts?

**Comment by Poslovitch** [comment]
@tastybento I agree with 1). I'll have a look into this, and let's see what it'll look like.

**Comment by tastybento** [comment]
@Poslovitch It will look like this:

```
# Command hook-in configuration.
# Level will try to hook into these commands when it starts
# If you have changed the default AcidIsland or BSkyBlock commands, change them here
acidisland:
  admin-command: acid
  user-command: ai
bskyblock:
  admin-command: bsbadmin
  user-command: island
```

I've made a branch with the change in it. Let me know what you think.

**Pull request merged**
